- 异常抛出的时候如果最终没有接受处理的地方，会跑到最顶级的栈里面，也就是main方法中体现出来，实在没人处理的话，就会自动调用printStackReace()方法并且结束程序运行。
那么我还有个问题， 多线程情况下的RuntimeException的表现遵循这个规则吗？