[上一页：1.7Java标准异常](/ThinkingInJava原版/异常捕获/1.7Java标准异常.md)
# 1.71 特例-RuntimeException

##### 示例：NullPointerException
我们康康下面的代码示例：
```
    if (null == t) {
        throw new NullPointerException();
    }
```

我想无论是源码还是自己写代码，恐怕会很少有人单独这样写，除非某些特殊的情况！
原因是如果对于所有你写过的代码都加上判空再抛出异常的话，代码会变得相当凌乱冗余，并且写一堆这样的代码恐怕没有什么提升价值。况且，你也不能知道所有可能为null的地方吧！是吧！幸运的是，Java平台标准异常有一个部分提供了，任何可能引发空指针的地方，java都会自动的抛出一个NullPointException

##### RuntimeException
与NullPointException相似的是，Java里面提供了很多类似的类，这些类不需要你特殊的声明什么，运行遇到了问题，会自动的抛出，不用用户去特殊的处理。他们有一个共同特点：**都继传承自RuntimeException**，当然如果你非要自己抛出，谁也拦不住你。语法上肯定是不会报错的。

##### RuntimeException 的处理
上面说了，系统会自动帮我们抛出一些RuntimeException。但是这类的exception，不晓得你有没有发现，系统是自动抛出的，那么这个异常的处理器在哪里呢？也就是try...catch代码块，咱们明明没有写啊。怎么处理的？不合规啊！！！
 - 对于RuntimeException这个特殊的异常，**<font color=#FF7F50>Java编辑器其实并没有强制我们一定要生手码try catch。</font>**
 - 在这种情况下，这种异常很可能直达main方法中，而不会被捕获！

**让我们看下面的例子**
```
/**
 * 电子书330页
 */
public class NeverCaught {
    static void f(){
        // 尽管你的代码中写了 throw 一个exception，但是编译器似乎未要求你一定在方法上写throws这个关键字
        throw new RuntimeException("From f()");
    }

    static void g() {
        // 尽管f中的逻辑 throw了一个异常，但是，编译器还是跳过了 try catch的检测！
        f();
    }

    public static void main(String[] args) {
        g();
    }
}
```
<font color=#FF7F50>如果一个RuntimeException直到顶级调用栈，即main方法，到了这里都没有碰到被捕获的情况！那么，该异常的printStackReace()方法，就会被系统自动的调用!!
并且已经经过验证，如果在Android中发生这种情况的话，程序就直接退出啦，也就是司空见惯的闪退现象出现!!</font>

##### 只有RuntimeException系列的异常，编译器才会忽略检查
原因是：
- 很多时候一个错误的产生是无法预料到的。例如常见的空指针问题
- 在开发过程中，往往真正出问题的地方不会暴露，反而引发了其他逻辑的不正常执行。例如常见的指针越界（ArrayIndexOutOfBoundsException!），有时候不小心就能出问题。在点1发生的异常通常称为点2的问题

[下一页：1.8用finally关键字进行清理](/ThinkingInJava原版/异常捕获/1.8用finally关键字进行清理.md)